version: '2'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    networks:
      - petclinic

  nginx:
    image: nginx:latest
    container_name: nginx
    build:
      context: ../..
      dockerfile: Dockerfile
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - petclinic

  petclinic_1:
    image: petclinic:latest
    container_name: petclinic_node_1
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - 9906
      - 3306
    networks:
      - petclinic


  petclinic_2:
    image: petclinic:latest
    container_name: petclinic_node_2
    ports:
      - 9906
      - 3306
    networks:
      - petclinic

networks:
  petclinic:
