version: '2'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    networks:
      - petclinic

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "7009:80"
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - petclinic

  petclinic_1:
    image: petclinic:latest
    container_name: petclinic_node_1
    build:
      context: petclinic
      dockerfile: Dockerfile
    ports:
      - "7002:8080"
      - "7004:3306"
    networks:
      - petclinic

  petclinic_2:
    image: petclinic:latest
    container_name: petclinic_node_2
    ports:
      - "7003:8080"
      - "7005:3306"
    networks:
      - petclinic

networks:
  petclinic:
